### ISSUE TITLE
Adding new improper torsions to .offxml, SMIRKS pattern match bug (forcefield.py)

### ISSUE THREAD

**Issue by jmaat** [openforcefield/openforcefield#106]
When trying to add the following improper torsion to my .offxml file: 
```<Improper smirks="[*:1]-[#7X3:2](-[#6a$(*1ncncc1):3])-[*:4]" id="i6" k1="1000" periodicity1="2" phase1="180."/>```

The following error occurred:
"does not specify a Improper torsion, but it is supposed to."

I commented out this part of the forcefield.py code and it got rid of the error. This piece of code most likely needs to be debugged:
https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/forcefield.py#L1721-L1727

**Comment by jchodera** [comment]
> When trying to add the following improper torsion to my .offxml file:

It looks like the XML tag defining the improper torsion you were trying to add wasn't successfully posted. Could you try posting it again?

**Comment by davidlmobley** [comment]
@jchodera - turns out we've stumbled across some SMIRKS patterns which can't yet be handled by ChemicalEnvironments, which does some checking to ensure that provided SMIRKS match the type of parameter they are being used for. Caitlin will have a look at this on Monday.

@jmaat - you'll have to paste your SMIRKS again (should be able to edit your comment above) as it didn't take properly.

**Comment by davidlmobley** [comment]
Actually, I can fix it! It's there in the text but just not displaying properly, one sec.

**Comment by davidlmobley** [comment]
@jmaat - GitHub uses Markdown style formatting; you can put code in single quotes (if it's a single line) or triple single quotes, if it's multi-line, to get it to be treated as and formatted as plain text so it will display properly, as was needed here.

**Comment by jchodera** [comment]
> Actually, I can fix it! It's there in the text but just not displaying properly, one sec.

Thanks!

The new `Topology` PR relies entirely on `ChemicalEnvironments` to parse whether the SMARTS string is valid (as well as determine what kind of valence term a tagged SMIRKS string specifies), so it will be great to figure out what is required to fix that.

**Comment by bannanc** [comment]
@jchodera
David meant he could fix Jessica's comment. I was out of town/internet
camping this weekend so I haven't had a chance to look at why these aren't
parsing correctly. If it's an easy fix I'll address it tomorrow, but if it
requires significant time then it will be longer due to SAMPL and MolSSI
deadlines that are both approaching quickly.
-- 
*****************************************
Caitlin C. Bannan
Ph.D. Candidate
Mobley Group
UC Irvine - Chemistry Department
bannanc@uci.edu
mobleylab.org

**Comment by bannanc** [comment]
Just to do a quick update, I believe I have found the specific bug, when parsing SMIRKS, I look for atoms not inside brackets, but the RegEx string currently only looks for aliphatic atoms, that is symbols in the form [capitol letter][lowercase letter] so it isn't catching the `*1ncncc1` part correctly. I'm working on fixing the code right now, I'll try to have a PR up tonight. 

@jchodera I'm working from your version of ChemicalEnvironments in the Topology PR because I didn't want to get conflicts with that. Will it make more sense for me to merge this into your branch, or just put the new ChemicalEnvironments into Master? (Or @davidlmobley)

**Comment by davidlmobley** [comment]
We want the fix in master, then if @jchodera wants to update his branch he can get it from there. I don't think there's really an ETA on getting his branch merged yet and this is something it would be good to fix sooner.

**Comment by bannanc** [comment]
OK, it I fixed the aromatic atoms fairly easily, but it looks like there is also a problem for how ring indices are identified when they're in the recursive SMIRKS so neither `1` in `*1ncncc1` is being put in the right place, I think I should be able to fix this fairly quickly in the morning, but I don't have time to get it done tonight.

**Comment by jchodera** [comment]
Thanks! I can merge back in from `master` when the fix is merged in.

**Comment by bannanc** [comment]
This should all be fixed by PR #108 Closing. @jmaat fyi
