### ISSUE TITLE
Add LGTM support?

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#142]
I've started using [LGTM](https://lgtm.com/) on [chemper](https://github.com/MobleyLab/chemper) to check for some good coding practices. I don't have much experience with it yet, but it looks useful to automate more checks in pull requests. 

Should we add it to openforcefield? @jchodera's group seems to be using it on some projects and might have an opinion. @j-wags?

**Comment by j-wags** [comment]
Very cool. I added the repo here:

https://lgtm.com/projects/g/openforcefield/openforcefield

I'm going to see if I can point it to specific branches, since that's where all the new code lives right now.

Let's leave this open for now, so we can come back and add the webhooks LGTM probably wants, as well as a badge.

**Comment by jchodera** [comment]
This appears to have been completed!
