### ISSUE TITLE
Expand error/warning message when undefined stereochemistry is detected

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#182]
Currently, we [return None](https://github.com/openforcefield/openforcefield/blob/topology/openforcefield/utils/toolkits.py#L730) when OpenEye can't figure out the chirality of an atom/bond and `exception_if_undefined_stereo is False` so it is impossible to ignore the warning.

I'll fix this in the next PR.

**Comment by andrrizzi** [comment]
May be related to #146 .

**Comment by j-wags** [comment]
Based on our conversation today, I agree that we should let a Molecule with undefined stereochemistry be returned if the user has specified `exception_if_undefined_stereo=False`. Otherwise the toolkit will just be too hard to use for some molecules. However I also agree that we should put in a longer message about why what they're doing is potentially dangerous, and stating that turning the check off to avoid a tetrahedral nitrogen could, for example, make them miss an important double bond missing stereo later in their test set.

**Comment by jchodera** [comment]
Are you sure you want to be calling [`OEPerceiveChiral` here](https://github.com/openforcefield/openforcefield/blob/topology/openforcefield/utils/toolkits.py#L677)?

The [documentation](https://docs.eyesopen.com/toolkits/cpp/oechemtk/OEChemFunctions/OEPerceiveChiral.html) says:
>  as a side-effect, it also sets the ‘symmetry’ property of all the atoms the molecule to be their ‘explicit hydrogen suppressed’ symmetry class, by calling the OEChem TK function OEPerceiveSymmetry.

That sounds dangerous!

Don't you just want to query the stereochemistry of sites after constructing them from a SMILES? 

Instead of letting users operate the toolkit with the safeties off just to deal with amines, what about instead detecting if you have a tertiary amine if OEChem thinks stereochemistry is undefined, and allowing that to be OK if so?

**Comment by j-wags** [comment]
@jchodera , that's a good catch. I've split that into its own issue.

This issue will be closed when
1) a more thorough warning message is implemented

**Comment by andrrizzi** [comment]
This was fixed in #182, but we still need to expand the warning message for this.
