### ISSUE TITLE
New to OpenForceField toolkit

### ISSUE THREAD

**Issue by pchau1807** [openforcefield/openforcefield#203]
Hello,

I am very new to OpenForceField toolkit. I has installed the toolkit based on this instruction: 
https://open-forcefield-toolkit.readthedocs.io/en/topology/installation.html
However, when I tried to import the SMIRNOFF Forcefield engine, it showed me this error:
No module named openeye
Warning: Cannot import openeye toolkit; not all functionality will be available.

Does it mean that I have to install OpenEye toolkit in order to use OpenForceField tookit? 

Can I use RDKit instead since in the API Documentation mentioned?
"1.3.11 TheopenforcefieldreferenceimplementationA Python reference implementation of a parameterization engine implementing the SMIRNOFF force fieldspecification can be found online.   This implementation can use either the free-for-academics (but com-mercially supported) OpenEye toolkit or the free and open source RDKit cheminformatics toolkit.  See theinstallation instructions for information on how to install this implementation and its dependencies."

Thank you so much for your time.

**Comment by j-wags** [comment]
Thanks for getting in touch. 

Right now, there's a little confusion because there are two versions of the toolkit:
* The 0.0.4 version is publicly available and is what you downloaded. This requires OpenEye and will not run with RDKit
* The 1.0.0 version is currently under development, and will support either OpenEye or RDKit. We're hoping to put out a public alpha release of that in the near future.

The link you shared points to an early version of the 1.0.0 toolkit documentation. I'm not sure how you found that (I hope we're not driving search engine traffic there!)

For documentation that is compatible with the current omnia conda package (which requires OpenEye), please see this page: https://open-forcefield-toolkit.readthedocs.io/en/latest/installation.html

**Comment by andrrizzi** [comment]
Closing this to keep the tracker clean, but feel free to reopen if you are still having issues.
