### ISSUE TITLE
Old Version of RDKit Installed when omnia above conda-forge

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#266]
When installing the `openforcefield` package from `omnia` in an environment which prioritises the `omnia` channel over `conda-forge` (whether this was done manually using `conda config` or within an `env.yml` file) using

`conda install openforcefield`

RDKit is by default is installed  from `omnia` at version 2015. This leads to a 
```
Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6
```
error when importing the `openforcefield` package, such as by:

`from openforcefield.typing.engines import smirnoff`

This issue can be fixed by either swapping `conda-forge` to be the top channel, or upgrading the RDKit package manually to 2018 or later.

Maybe this should be resolved by pinning RDKit to be greater than or equal to V2018 or later in the released version?

**Comment by j-wags** [comment]
I tried to find why Travis wasn't having trouble with this setup, but was unsuccessful. I couldn't find in the travis build logs where it listed which rdkit version was being pulled in. Note also that this issue might relate to #237, since installation of these bad versions might be masked by the redundancy between the `RDKIT` variable in our testing matrix, and the fact that rdkit is now included in our testing environment YAML.

Regardless, a fix for this behavior would be to pin `rdkit > 2016`, since the newest version on `omnia` is 2015.

**Comment by jchodera** [comment]
We can always delete the omnia rdkit if it's causing problems. I don't think anything used it except for an ancient version of deepchem.

**Comment by j-wags** [comment]
If it won't have any bad side effects, removing rdkit from omnia would be really nice. As long as it's there, I think folks with custom environments will keep running into this issue.

**Comment by jchodera** [comment]
I've moved the `omnia` builds of `rdkit` to the `legacy` label:
https://anaconda.org/omnia/rdkit/files

**Comment by SimonBoothroyd** [comment]
> I've moved the `omnia` builds of `rdkit` to the `legacy` label:
> https://anaconda.org/omnia/rdkit/files

This seems to have fixed things. Unless any one wants to do any further testing, I think this issue can be closed?

**Comment by andrrizzi** [comment]
Thanks for checking, @SimonBoothroyd !
