### ISSUE TITLE
Decide how to handle water models with extra sites

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#27]
I just realized that we have no support for TIPnP models of water where n is higher than 3 at present, because SMIRNOFF currently uses only an all-atom representation of molecules (though coarse-grained representations are planned). There are plans for virtual sites for off-center charges in the format, however, but none are supported yet.

@jchodera - what's the easiest way to get in support for water models with more than three sites?

**Comment by jchodera** [comment]
We do have [planned support for virtual sites](https://github.com/open-forcefield-group/smarty/issues/132), but I don't believe our spec actually would allow us to implement TIPnP models. 

I suggest we
* extend the [proposed spec](https://github.com/open-forcefield-group/smarty/issues/132) to easily handle TIPnP models
* implement the specific part of that proposed spec now, since OpenMM already supports the virtual site capabilities we need

**Comment by davidlmobley** [comment]
I agree with this, though I don't necessarily think it has to be **now** as opposed to **soon**.

**Comment by davidlmobley** [comment]
This is decided, it's just that we need virtual sites in order to proceed with TIPnP for n>3. @j-wags I think this can be closed.
