### ISSUE TITLE
Outdated code in tests

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#387]
I was searching the code to figure out how to get/set parameters at present, and searched for the "getParameter" option (which is apparently no longer avaialble). However, it appeared that it IS still available since there is still code in the tests which utilizes this, e.g. https://github.com/openforcefield/openforcefield/blob/35b54c5acb5d9e635caa2a9123b336e51095ece5/openforcefield/tests/test_smirnoff.py#L504-L517

We should remove code from the tests when it is no longer supported.

**Comment by j-wags** [comment]
Agree that this should be cleaned up. Let's touch on this during post-0.6.0 housekeeping.

Context: These tests were kept around because we weren't sure which functions we wanted to save from `utils/structure.py` (#333), and we could reuse these tests if we decided to keep certain functions. There seemed to be a good idea of which ones to remove, so we should try to be good API maintainers and add deprecation warnings in 0.5.0 or 0.6.0. This would give us a heads-up if any of our users would prefer that we maintain this functionality.

**Comment by jchodera** [comment]
That's odd---how did this slip by? We should definitely expunge tests that aren't being actively run by CI.

**Comment by j-wags** [comment]
Adding pending-deprecation warnings about utils/structure.py in #425

**Comment by mattwthompson** [comment]
I think this can be closed now that the `utils.structure` module is removed (a change that will be reflected in the 0.8.0 release)

**Comment by j-wags** [comment]
Agreed. Closing!
