### ISSUE TITLE
Make an example notebook/script that analyzes molecule dataset coverage

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#413]
It should take as input a large number of molecules in various formats (SDF, SMILES, MOL2 if OETK is available) and return useful info about if any of the molecules would not have been parameterizable.

*NOTE*: It is not necessary to generate openMM systems for these molecules, so we don't have to perform charge generation

A stretch goal would be that companies with proprietary molecule datasets could use this tool locally and easily report missing coverage, without releasing the whole molecule of interest.

**Comment by davidlmobley** [comment]
I'd also had a related thing where I wanted to add visualization of where parameters are missing via highlighting on 2D structures. Some of Caitlin's earlier examples had highlighting depictions and I can dig these up if this is something we want in your notebook (otherwise I'll save it for when I get around to adding this myself).

**Comment by davidlmobley** [comment]
Also, I'd done something rather similar to what you're proposing to work through a bunch of eMolecules molecules which fail to minimize with SMIRNOFF. It's not elegant, but I'm providing below:
- Noteboook I was using
- List of molecules which fail (many because of parameter coverage issues)


[problem_smiles.txt](https://github.com/openforcefield/openforcefield/files/3575868/problem_smiles.txt)
[check_molecules.ipynb.zip](https://github.com/openforcefield/openforcefield/files/3575870/check_molecules.ipynb.zip)
