### ISSUE TITLE
Update to AmberTools19 (or ambermini variant)

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#423]
Now that [AmberTools19 is out](http://ambermd.org/AmberTools.php) we should update to this version or work with the Amber folks to use an ambermini equivalent.

**Comment by j-wags** [comment]
Agree -- Let's reopen this discussion. 

Basically, there are a lot of "pro"s to this idea, and the big con is that it would make the downloads for our `conda install openforcefield` ~120MB larger. But I can't think of many people for whom 200MB is doable but 300 isn't. And, as an added plus, downloading all of AmberTools gets us `sander`, which we could include in examples.

I'll start experimenting with the new AmberTools package. One big positive side effect of switching to depend on the AmberTools conda package is that we'll get new features (like the WBO code) as soon as it's available, rather than needing to wait for a second package to be updated (or updating it ourselves).

Dave Case had left some really good feedback earlier (#153), which I wasn't in a position to understand at the time, but I've since learned enough about packaging to have an opinion. I'll start collecting my thoughts to post in that thread.

**Comment by j-wags** [comment]
Closing this thread in favor of #153
