### ISSUE TITLE
Cannot create complex parsley system

### ISSUE THREAD

**Issue by Alikusay** [openforcefield/openforcefield#457]
Hello,

I hope that I haven't missed something obvious, but I am struggling to create an openmm system by combining a ligand and protein structure, I have been following the "toluene_in_T4_lysozyme.ipynb" exmaple.

After combining the ligand and protein structures, attempting to create an OMM system fails with:
"AttributeError: 'NoneType' object has no attribute 'req'"

This seems to be related but slightly different from an issue in #444, I have used the same jupyter jupyter-notebook in this issue, ensuring to include the HBond constraint during system creation. I noticed that the issue seems to come from the "None" type bonds between ligand carbon and hydrogen atoms, is this normal?

Jupyter-notebook: https://gist.github.com/Alikusay/e29bf0856dca84f71cf0535374ea13b9

Would appreciate any help, thank you.

**Comment by Alikusay** [comment]
I should have paid more attention to the previous post, sorry! 

It works fine with the openforcefield without Hbond length constraints:
ff = ForceField('openff_unconstrained-1.0.0.offxml')

**Comment by j-wags** [comment]
Hi @Alikusay ,

Thanks for the report and attached notebook, and extra thanks for linking a related issue. I'm able to reproduce your error on my computer. 

Similar to #444, I can fix it by loading the "unconstrained" Parsley FF -- `ff = ForceField('openff_unconstrained-1.0.0.offxml')`. To be clear -- _The resulting system will still have hbond constraints_, since we're also including `constraints=app.HBonds` in the final step.

We understand that this is confusing, and it is due to some tricky assumed behavior at the interface of OpenMM/ParmEd/OpenForceField. Moving forward, we're hoping to add new objects that just "do the right thing" and avoid this issue. 

Please let me know if this resolves your problem!

**Comment by j-wags** [comment]
Glad it worked out for you. Apologies again for the odd behavior -- I hope we can roll out our own objects in a future release to make this simpler.
