### ISSUE TITLE
Remove generateTopologyFromOEMol?

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#48]
In the OpenMM OpenEye stack, there's now support for roundtripping molecules from OEMol to OpenMM and back (see https://github.com/open-forcefield-group/openforcefield/issues/47#issuecomment-309589618 ); should we remove the `generateTopologyFromOEMol` function in favor of using the functionality there? Though, we'd presumably need to make sure that the relevant toolkits are then conda installable.

The functionality there is, I believe, superior, in that it handles molecules that may consist of multiple residues, etc., whereas we currently handle only small molecules that consist of a single residue.

**Comment by jchodera** [comment]
What is "the OpenMM OpenEye stack"?

**Comment by jchodera** [comment]
And can you be more specific about which functions you are proposing using instead?

**Comment by davidlmobley** [comment]
@jchodera - as per the link (sorry, I was being lazy and should have put the links here):
[oemol_to_openmmTop](https://github.com/oess/openmm_orion/blob/master/ComplexPrepCubes/utils.py#L126)

and

[openmmTop_to_oemol](https://github.com/oess/openmm_orion/blob/master/ComplexPrepCubes/utils.py#L192)

The OpenMM OpenEye Stack: https://github.com/oess/openmm_orion

**Comment by jchodera** [comment]
These functions look like improvements over the current `generateTopologyFromOEMol()` and friends, but we definitely do not want to (1) depend on generic tools inside a specialized Orion cube (which should contain only the bare essential code required to glue a library into a cube), and (2) something that isn't a conda-installable library.

We should be moving all of these functions into a more general conda-installable library layer that both `openforcefield` and OpenMM Orion cubes can reliably use. I'm thinking the [`openmm-forcefields`](https://github.com/choderalab/openmm-forcefields) package is one option for this, since I'd love to support OpenEye in the OpenMM 7.2 release. Alternatively, we could create an `oechem-openmm` OEChem-OpenMM compatibility library specifically for tools that enable interoperability and use that in both projects. We might even get OpenEye to help maintain such an interoperability layer.

**Comment by davidlmobley** [comment]
@nividic @cbayly13 - you should refer to the above when you have time and get back to us with thoughts.
