### ISSUE TITLE
context update exception

### ISSUE THREAD

**Issue by matteo-ambrosetti** [openforcefield/openforcefield#584]
**Describe the bug**
Hi everyone,
I am trying to perform an MD simulation of a solute-in-solvent system. I need to keep freezed the geometry of the solute and to do this I am relying on a script (rigid.py) from Peter Eastman which implements rigid bodies. To avoid intramolecular interactions I am acting on `force.getExceptionParameters()` to set both charges and LJ parameters to 0.0. Unfortunately when I try to update the context I get the following error:

`Exception: updateParametersInContext: The number of non-excluded exceptions has changed`

I have also noticed that if the parameters are already 0.0 no exception is raised.

**To Reproduce**
Pleas find attached a code to reproduce the error.
[error.zip](https://github.com/openforcefield/openforcefield/files/4510083/error.zip)

**Comment by jchodera** [comment]
@matteo-ambrosetti : This is an OpenMM specific problem, so it's best to use the [OpenMM issue tracker](http://github.com/openmm/openmm/issues) for further questions, but there's an easy fix for your problem:  

OpenMM treats charge and LJ `epsilon` parameters of `0.0` as exceptions, so the better approach is to instead set this to a small number (e.g. `1.0e-8`) that is still non-zero. 

Also, it's best to only change LJ `epsilon`, and not `sigma` since this can sometimes cause numerical instability because `sigma` appears in the denominator of some expressions.

**Comment by davidlmobley** [comment]
I believe this can be closed, but please re-open if you need further assistance with `openforcefield`.

**Comment by matteo-ambrosetti** [comment]
Thanks @jchodera, and sorry for the delayed answer. I am aware of the solution of using a small number instead of 0.0 (which is what I have done in error.zip), but it doesn't work for me anyway. I will move this issue to the [OpenMM issue tracker](https://github.com/openmm/openmm/issues).
