### ISSUE TITLE
Error converting via parmed to prmtop, related to ParmEd #930

### ISSUE THREAD

**Issue by rmcgibbo** [openforcefield/openforcefield#603]
**Describe the bug**
I'm not very experienced with this software stack, so apologies in advance if I'm filing this issue in the wrong place. I'm seeing an error which is identical to one reported in https://github.com/ParmEd/ParmEd/issues/930 a couple years ago that comes when trying to parameterize a system with openff and then save the results in prmtop format.

I was trying to roughly follow the example here: https://github.com/openforcefield/openforcefield/blob/master/examples/using_smirnoff_in_amber_or_gromacs/convert_to_amber_gromacs.ipynb

**To Reproduce**
```
import parmed
import numpy as np
from openforcefield.topology import Molecule
from openforcefield.typing.engines.smirnoff import ForceField

ethanol = Molecule.from_smiles("CCO")
forcefield = ForceField("./openforcefields/openforcefields/offxml/openff-1.1.1.offxml")
random_positions = np.random.randn(9, 3)

openmm_topology = ethanol.to_topology().to_openmm()
openmm_system = forcefield.create_openmm_system(ethanol.to_topology())

structure = parmed.openmm.load_topology(openmm_topology, openmm_system, random_positions)
structure.save("example.prmtop")
```

**Output**
```
$  python repro.py 
Warning: In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule '' has more than one conformer, but this function will only generate charges for the first one.
Traceback (most recent call last):
  File "repro.py", line 14, in <module>
    structure.save("example.prmtop")
  File "lib/python3.7/site-packages/parmed/structure.py", line 1506, in save
    s = amber.AmberParm.from_structure(self)
  File "lib/python3.7/site-packages/parmed/amber/_amberparm.py", line 350, in from_structure
    inst.remake_parm()
  File "lib/python3.7/site-packages/parmed/amber/_amberparm.py", line 677, in remake_parm
    self._xfer_bond_info()
  File "lib/python3.7/site-packages/parmed/amber/_amberparm.py", line 1581, in _xfer_bond_info
    bond.type.used = True
AttributeError: 'NoneType' object has no attribute 'used'
```

**Computing environment:**
 - openforcefield top-of-tree, parmed 3.2.0

------------

Based on experimenting, https://github.com/openforcefield/openforcefield/issues/259, and https://github.com/ParmEd/ParmEd/issues/868, I suppose this is a know issue, and the conclusion is that the best route is to use the unconstrained version of OpenFF and then add the constraints at a later point.

My questions are:
(a) Is this diagnosis correct?
(b) Is there anything that can be done to improve this behavior?

**Comment by jchodera** [comment]
(a) Yes! If you want to convert through `parmed`, you need to use the unconstrained version of the `offxml` file so ParmEd receives the bond parameters (even if they are constrained later).

(b) By "improve", could you clarify what you would like to happen? Constrained systems do not have parameters for bonds in the OpenMM `System` object, so there are none by the time it is read by ParmEd. Since bond constraints are specified to AMBER's `sander` in a separate `md.in` file, constraints do not appear within the `prmtop` file, and hence ParmEd would need to "make up" parameters out of thin air if this behavior was to be improved with the existing object flow.

We're working on a new interoperable `System` object that is pure python and would hold parameters assigned to a system that mirror the SMIRNOFF  parameter model. Once we have established this, it will be possible to directly convert to many formats by simply iterating over the objects in this model and writing them out in the appropriate (perhaps lossy) destination formats. We also hope to develop a library for interoperating with this object model so that software packages could simply link this library to gain access to reading and using the object model directly in the longer term.

**Comment by rmcgibbo** [comment]
> We're working on a new interoperable System object that is pure python and would hold parameters assigned to a system that mirror the SMIRNOFF parameter model. 

Sounds good.

> (b) By "improve", could you clarify what you would like to happen?

It would be ideal if either the information could be transmitted through, one of the layers in this stack could throw a more informative error message, but I understand that that's much easier said than done.

**Comment by jchodera** [comment]
> It would be ideal if either the information could be transmitted through, one of the layers in this stack could throw a more informative error message, but I understand that that's much easier said than done.

Since ParmEd is open source but unmaintained, I'll just say that PR's are likely welcomed there!

However, ParmEd has a very AMBER-centric object model, making it difficult to shoehorn in information (such as bond constraints) that simply do not exist in the AMBER object model.

We're trying our best to remedy this with a new, maintained, well-supported and modular approach that eliminates some of the limitations with the AMBER-centric object model.
