### ISSUE TITLE
CI Failing on Master

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#621]
**Describe the bug**
The CI tests which include `rdkit` are currently failing on master since 4 days ago. This roughly coincides with a new release of [Rdkit on conda-forge](https://anaconda.org/conda-forge/rdkit/files).

**Comment by mattwthompson** [comment]
I've found that QCEngine's deps (https://github.com/MolSSI/QCEngine/issues/252, fixed in https://github.com/MolSSI/QCEngine/pull/253) which happened to introduce an API-breaking change at a time near RDKit's recent release. Everything is passing for me locally now.

I fear this will require a QCEngine bump before 0.7.0. Pinning an implicit dependence to a lower version is the only alternative I can think of, and that is not appealing.

**Comment by mattwthompson** [comment]
And just to resolve my confusion ("why does this QCEngine issue only show up in RDKit tests?") the example is skipped when RDKit is not installed, and this is encoded in the GHA script:

https://github.com/openforcefield/openforcefield/blob/3de67ca96265a3953c008e8e244c380d4aa81f2e/.github/workflows/CI.yml#L105-L115

**Comment by mattwthompson** [comment]
Fixed for now (save one codecov step, the recent cron CI passed). Thanks for catching this @SimonBoothroyd!
