### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#637]
**Describe the bug**
The [0.7.0 API docs](https://open-forcefield-toolkit.readthedocs.io/en/0.7.0/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule) don't render and link to method API docs as they should.

**To Reproduce**
Go to https://open-forcefield-toolkit.readthedocs.io/en/0.7.0/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule and try to click on the method names.

**Comment by j-wags** [comment]
Closing as duplicate to #602, where I approved breaking these links in order to unblock the 0.7.0 release (since the sphinx 3 release had broken everything, and RTD doesn't let us downgrade sphinx). 

Looks like someone has started hosting a fork of the abandoned `m2r` project (called `m2rr`). It's pypi-only right now, but that's not a bad start. https://github.com/qhua948/m2rr
