### ISSUE TITLE
Add `atom.is_in_ring` and `bond.is_in_ring`

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#679]
We’ll need an RDKit-backed or toolkit-agnostic `atom/bond.is_in_ring` for fragmenter migration

* Maybe SMARTS syntax using rN can do this? Or does that only check for specific values of N? 
* Maybe there’s also some method call involving SSSR that can do this?
* Maybe NetworkX can do this? find_cycles or something?
    * Are there some cycle sizes that are ignored or treated specially by OETK or fragmenter? What about 3- or 4-membered rings? We should aim to replicate this behavior precisely in the first iterations.
* Do we anticipate needing any special behavior for macrocycles? Or is that outside the scope of this work?

**Comment by mattwthompson** [comment]
> Maybe SMARTS syntax using rN can do this? Or does that only check for specific values of N?

[`R<n>`](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) checks for ring membership (in `n` numbers of rings, disregarding size), which can probably be used to this end. It may require some hard-coding of `R1`, `R2`, `R3`, etc. if the meaning of "not R0" cannot be encoded.

> Maybe NetworkX can do this? find_cycles or something?

It requires putting my thinking cap on to refresh my memory of what actually happens here, but I think [this](https://github.com/mosdef-hub/foyer/blob/12e9e6d567be321a9d977c335c9f6422af04887b/foyer/smarts_graph.py#L244) code in foyer does that. Note the linked StackOverflow thread. There may be something `networkX` can do more directly.

> Are there some cycle sizes that are ignored or treated specially by OETK or fragmenter? What about 3- or 4-membered rings? We should aim to replicate this behavior precisely in the first iterations.

A potentially related issue is that the function I linked above can find multiple rings; naphthalene can be thought of as having two 6-member rings and a single 10-membered ring, so that function defaults to only looking for rings of size 8 or fewer. This would require some thinking about the edge cases, in particular small rings being fused together.

**Comment by mattwthompson** [comment]
There's a lot of discussion in the linked PR, but to summarize:

* An RDKit-only method was used to find the rings in a molecule, from which atoms and bonds have a boolean `is_in_ring` property
* This method is likely to find all rings for most structures, but will miss some rings when multi-cyclic moieties like in norbornane are present
* This method guarantees (or nearly so?) that a bond or atom will know if it is in a ring, but possibly not all rings it is in (i.e. in above cases in which an atom is technically in multiple rings) but that should not have a major impact on the property as it is a boolean.
