### ISSUE TITLE
How to best expose rdkit SMIRNOFF to the user?

### ISSUE THREAD

**Issue by hjuinj** [openforcefield/openforcefield#69]
I guess it is good if we discuss and decide on how to expose rdkit SMIRNOFF to the end users. 

At the moment, I just have a separate class called `forcefield_rdk` and a user will call that class instead of `forcefield` if they wish to use the rdkit version, and I am putting all import statements in SMIRNOFF concerning openeye products into try blocks.

**Comment by jchodera** [comment]
The right approach to this is likely to add a layer of indirection between any of the calls from `ForceField` that require one of these toolkits (openeye or rdkit) and the actual calls to toolkit. That way, `ForceField` will not call *either* toolkit directly, but instead call methods in a utility chemical perception and molecule handling class which handles anything that talks to the toolkit.

We don't necessarily want to rewrite a whole abstract `OEMol`-like layer, so we should first determine the smallest number of major operations that interact with the `OEMol`s and then define the abstraction API around this.

Alternatively, we could switch entirely to RDKit because it is fully open source (which matches our goals), but my gut feeling is that the science will be *much* more rapid using the OpenEye toolkit. On the other hand, we'll likely need to have switched to some entirely open source platform by mid-2018.

**Comment by davidlmobley** [comment]
I think @jchodera is right here, though I understand that likely, @hjuinj , you will have to draw a line somewhere in terms of how much you are able to do versus what you want to pass off to us (though we'd love it if you want to be one of us for the long haul as well!).

It seems to me like there are a couple possible limiting scenarios for your involvement:
1) Minimal: You just finish your `ForceField_rdk` class which basically acts like `ForceField` but uses RDKit, then hand it off to us to sort out how we want to abstract the chemistry aspects out of it;
2) Extensive: You finish off as in (1) but then help us sort through how to abstract out the chemistry operations and get an implementation working which does this

Possibly you'll be somewhere in between those two extremes...?

Without reviewing code/details, I'm thinking offhand that the key places where we use chemistry toolkits are:
- substructure searching (most obvious and most important)
- partial charge assignment
- sanity checks on input molecules (as we're discussing here: https://github.com/open-forcefield-group/openforcefield/issues/61 ) 
- "advanced features": Partial bond orders

There would be also various other places you need chemistry if you're doing molecule preparation, though as noted in #61 we want to make sure molecule preparation is not automatically done by `forcefield` so that expert (or even normal) users don't have to worry it will be changing their chemistry on them if they are putting in a molecule which is already prepared. We just want to be sure `forcefield` has suitable warnings in place if someone puts in something which is clearly "bad chemistry" and give utility functionality that can be used to help prepare molecules when needed.

**Comment by hjuinj** [comment]
Hi David,

I would love to stay on and continue helping with the open forcefield initiative development. I think it is a great learning experience for me :)

**Comment by davidlmobley** [comment]
Great, @hjuinj . That also should be helpful as (given your current position) you can hopefully help us broaden our user base into Europe (and other communities) as this grows. :)

**Comment by davidlmobley** [comment]
So, basically, what that means is that we should help think through how exactly to do the more extensive changes to get these seamlessly linked up. Nag me when you're ready to do that and I'll try and help.

**Comment by jchodera** [comment]
How about this:

My group (in NYC) to sit down and go through the `forcefield.py` code in detail and identify opportunities for a major refactor, isolating the OpenEye-specific calls in a few specific functions. We can then do that overhaul (likely as early as this weekend) and walk @hjuinj through the changes and updated docs next week. At that point, it should be easy to create RDKit versions of these functions from the current `forcefield_rdk` implementation.

**Comment by davidlmobley** [comment]
Sounds fine to me, @jchodera . Note at the same time you may want to speed up parsing via #51 and perhaps also take care of #52.

**Comment by davidlmobley** [comment]
@jchodera 
> My group (in NYC) to sit down and go through the forcefield.py code in detail and identify opportunities for a major refactor, isolating the OpenEye-specific calls in a few specific functions. We can then do that overhaul (likely as early as this weekend) and walk @hjuinj through the changes and updated docs next week. At that point, it should be easy to create RDKit versions of these functions from the current forcefield_rdk implementation.

Can you give an update on this? @hjuinj is waiting for you before proceeding any further, so if this has been put on the back burner it's probably good to let him know so that he makes different plans rather than continuing to wait.

Thanks.

**Comment by jchodera** [comment]
I think we'll be able to go through this either Tue or Wed morning to get this set up for @hjuinj.

**Comment by davidlmobley** [comment]
Resolved by big topology revamp.
