### ISSUE TITLE
Lingering issues relating to an RDKit implementation

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#70]
As I understand it, @hjuinj is making fairly good progress towards an RDKit implementation (see #69 ) , in that his prototype RDKit version can give identical parameter assignments for the majority of DrugBank with only a couple lingering issues on the RDKit end (both of which are quite significant, though):

1) We currently rely on the MDL aromaticity model, which is not implemented in RDKit and we are unsure how to do so (the information on setting up a custom aromaticity model is minimal) so we need some guidance from the RDKit developers before we can proceed further (https://github.com/rdkit/rdkit/issues/1622 )

2) RDKit doesn’t fully support input of molecules from mol2 format unless they have Corina atom types (though they PARTIALLY support some molecules with SYBYLY/TRIPOS types), but the tools commonly used in molecular simulations don’t assign Corina atom types, nor am I aware of an open source tool which does. This poses major problems for getting molecules INTO RDKit. The folks I’m aware of who have dealt with this so far have bypassed the issue either by (a) pre-processing all of their molecules with the OpenEye tools; it seems that mol2 files output by the OpenEye tools are often (but not always) correctly handled by RDKIt, or (b) reading mol2 files of their molecules with the OpenEye toolkits and then converting the OEMols into RDMols. Neither of these is a general solution, since someone wanting an RDKit version presumably does so because they don't have the OpenEye tools. The only general solution I see is to get RDKit to provide a better/more general mol2 reader, as bypassing mol2 entirely is not really a viable option.

There is also a third issue which doesn’t directly involve RDKit necessarily — how will we assign partial charges for small molecules in general? We need a conda-installable open source tool to assign AM1-BCC charges or similar. 

Anyone interested in contributing here (in terms of discussion/ideas, or coding help) is welcome.

**Comment by jchodera** [comment]
> There is also a third issue which doesn’t directly involve RDKit necessarily — how will we assign partial charges for small molecules in general? We need a conda-installable open source tool to assign AM1-BCC charges or similar.

We can use [`ambermini`](https://anaconda.org/omnia/ambermini) and the now-conda-installable [`ambertools`](http://ambermd.org/#AmberTools) to assign AM1-BCC charges for now, but we will eventually want to replace these with a better tool that doesn't require legacy compiled `antechamber` and `sqm` code.

For the other issues, I suggest we set up a call with Greg Landrum.

**Comment by davidlmobley** [comment]
Do you want to initiate, @jchodera , since he doesn't know me?

**Comment by greglandrum** [comment]
Adding a "flavor" argument to the mol2 reader to support an alternate set of semantics for some/all of the atom types is work, but it's likely not hugely complicated.

**Comment by davidlmobley** [comment]
@greglandrum - is there someone on your end who might be interested in this (e.g. if I raise an issue on the issue tracker) or, if not, maybe you can sketch a brief outline of what would be involved? We're RDKit newbs. 

The main issue here is just that (classical) molecular modeling people tend to often need (and require for small molecules) a file format which carries around partial charges with it, which means most of our packages rely a lot on `.mol2` for small molecules. RDKit's current level of support for reading `mol2` (though understandable) causes us a considerable amount of headache at present if we want to use it. 

One concrete example is the issue with charging @jchodera just mentioned -- we can use `ambertools ` to get the AM1-BCC charges we need, but our input to `ambertools` has to be a `mol2` file with either GAFF or SYBYL atom types, and the output will ALSO be a mol2 file with GAFF or SYBYL atom types. Corina types are a no-go. We don't actually want to use the atom types for anything and we don't particularly care what they are as long as the chemistry is perceived correctly, but...

**Comment by greglandrum** [comment]
Various levels of interest have come up for there being support for different mol2 readers or a mol2 writer (there's actually an open PR for this). I wouldn't have any objection to having another reader flavor added, particularly since it seems to address a real need, but I don't know who would do the work. I'd be willing to help out and point people to the relevant bits of code (and try to explain those), but I am probably not the guy to do the actual implementation. I think we'd really need someone who works with this pretty frequently so that they understand the odd edge cases that will come up and can do the testing that will be required.

**Comment by jchodera** [comment]
@davidlmobley : Realistically, I think we'll likely need to budget time for someone (or a couple of people) on our end to make the necessary contributions to RDKit here, with pointers from @greglandrum to save time and hit those edge cases. This would also be a good way to give back to the community if we're going to lean heavily on the RDKit as a basis for the Open Forcefield effort being truly open.

**Comment by davidlmobley** [comment]
@jchodera - I agree that once we have funding, that would be something we would want to try to do. 

At present, we're more in a situation where we are on the verge of having a useful RDKit implementation of this except for the facts that:
a) molecular simulations people won't be able to use it if RDKit can't read their mol2 files, and
b) we can't quite finish getting it to work until we sort out the aromaticity issue

One might hope we could make progress on these -- especially the aromaticity issue, which seems the easier of the two -- sooner while the funding is being sorted out.

**Comment by greglandrum** [comment]
Yeah, I think the aromaticity addition should be pretty straightforward (and something I can do) if we have a clear idea of what actually is aromatic in the "MDL" model. The RDKit issue is the place for that discussion.

**Comment by davidlmobley** [comment]
Thanks, @greglandrum . I'm working on getting a clearer description -- I'm a physicist by training myself, so I have my student @bannanc (who is a proper chemist) refreshing her memory. :)

**Comment by bannanc** [comment]
Since @davidlmobley is referring to me as a "proper chemist" what I was actually trying to remind myself of was what I was told by more senior chemists last summer. The only aromaticity model I was taught is Huckel, I know "MDL" doesn't define fused 5 member heterocycles as aromatic, but I'm not sure what other exceptions or differences there may be. 

I've been trying to do some literature and google searching this evening for the MDL model. I've found a few sites/papers that talk about supporting multiple aromaticity models, but so far none of them actually define the differences in these models.

**Comment by greglandrum** [comment]
Since the primary interest at the moment is having software that works with either the RDKit or OEChem in the background, I think what's needed here is more of an OE_MDL model: a reimplementation of what is meant by "MDL" in the OEChem software. 

An actual implementation of what MDL considers aromatic (if you can find a copy of their "Chemical Representation Guide" it's in there) would also be interesting, but may not help the open forcefield work that much.

**Comment by davidlmobley** [comment]
Yes, @greglandrum - since we want to be able to use either chemistry engine under the hood, an "equivalent" aromaticity model would be ideal. I'm just not totally sure that their docs are clear enough on what's going on that it's enough to go on.

**Comment by bannanc** [comment]
I started with the OpenEye documentation for the aromatic models:
https://docs.eyesopen.com/toolkits/python/oechemtk/aromaticity.html#chapter-aromaticity 
This is the most thorough description of the MDL model I have been able to find, it has a variety of examples, but no set of "rules."

**Comment by jchodera** [comment]
Here's the OpenSMILES spec, which includes an alternative (but open and documented) [aromaticity definition](http://opensmiles.org/opensmiles.html#inaromaticity): http://opensmiles.org/

**Comment by jchodera** [comment]
I think this has been resolved! Please reopen if not.
