### ISSUE TITLE
Missing bond types when converting a system to GROMACS top file 

### ISSUE THREAD

**Issue by asgharrazavi** [openforcefield/openforcefield#731]
I have created a system using Charmm force filed and converted in into GROMACS `gro` and `top` file as suggested in [this ](https://github.com/openforcefield/openforcefield/blob/master/examples/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb) example.  While doing this, I only get the following warning messages:

<pre>
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:451: OpenMMWarning: Detected incomplete exceptions. Not supported.
  warnings.warn('Detected incomplete exceptions. Not supported.', OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomBondForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
</pre>

However, when I use GROMACS to minimize the system, I get these errors:

<pre>
ERROR 1 [file prot.top, line 5644]:
  No default Bond types

ERROR 2 [file prot.top, line 5645]:
  No default Bond types

ERROR 3 [file prot.top, line 5646]:
  No default Bond types

ERROR 4 [file prot.top, line 5649]:
  No default Bond types

ERROR 5 [file prot.top, line 27311]:
  Atomtype 1.007947 not found
</pre>

Looking at the `top` file, there are empty values for lines where above errors occur:
<pre>
      1      5     1   0.11110 269449.600000
      1      6     1   0.11110 269449.600000
      1      4     1
      1      5     1
      1      6     1
      1      2     1   0.14900 209200.000000
      2      3     1   0.12300 518816.000000
</pre>

I was wondering if these empty values and warning messages printed by ParmEd are related and if so, how to fix it?

**Comment by j-wags** [comment]
Thanks for writing in, @asgharrazavi.

@mattwthompson, @davidlmobley, or @mrshirts probably know more about GROMACS compatibility specifically, but I may be able to help a bit. 

One possible resource is [this example of running a GROMACS simulation of an openFF ligand](https://github.com/openforcefield/openforcefield/pull/403). It's languished in a PR for a while because we haven't figured out how to integrate GROMACS-dependent routines into our toolkit. I'll start looking into whether the above example reproduces your error, though you might recognize something it does that could fix your issue. 

Some other things that you could do to help us debug would be to:
* Provide the code and files that are producing the error you're getting (can attach them to a GH issue as a tar)
* Provide the output of running `conda list` in your openff environment

**Comment by mattwthompson** [comment]
This is a ParmEd bug that I keep forgetting to report. IIRC, the analogous behavior with AMBER produces a descriptive error before writing out bad files, so the user doesn't have to parse `gmx grompp` errors and then dig through files to find incorrectly-written lines. I'm not sure off the top of my head what the best route toward a fix would be, but an error should be raised somewhere along the pipeline.

**Comment by asgharrazavi** [comment]
I think there is a problem when creating a openmm system using `parmed.openmm.load_topology`. Here is a simple example:

PDB:

<pre>
CRYST1   41.604  116.842   91.486  90.00  90.00  90.00 C 2 2 21      8
MODEL        1
ATOM      1  CY3 MET A   1      35.416   9.009 -18.663  1.00  0.00           C  
ATOM      2  CY  MET A   1      34.218   9.958 -18.693  1.00  0.00           C  
ATOM      3  OY  MET A   1      33.432   9.978 -17.748  1.00  0.00           O  
ATOM      4 1HY  MET A   1      35.403   8.426 -17.715  1.00  0.00           H  
ATOM      5 2HY  MET A   1      35.362   8.313 -19.530  1.00  0.00           H  
ATOM      6 3HY  MET A   1      36.359   9.596 -18.727  1.00  0.00           H  
ATOM      7  N   MET A   1      34.018  10.791 -19.775  1.00 20.33           N  
ATOM      8  CA  MET A   1      32.868  11.699 -19.798  1.00 18.20           C  
ATOM      9  C   MET A   1      31.568  10.891 -19.713  1.00 15.92           C  
ATOM     10  O   MET A   1      31.352   9.991 -20.514  1.00 14.01           O  
ATOM     11  CB  MET A   1      32.903  12.559 -21.061  1.00 21.42           C  
ATOM     12  CG  MET A   1      31.963  13.738 -21.031  1.00 25.49           C  
ATOM     13  SD  MET A   1      32.638  15.208 -21.861  1.00 31.29           S  
ATOM     14  CE  MET A   1      32.598  14.706 -23.443  1.00 28.17           C  
ATOM     15  HN  MET A   1      34.664  10.775 -20.551  1.00  0.00           H  
ATOM     16  HA  MET A   1      32.926  12.355 -18.930  1.00  0.00           H  
ATOM     17  HB3 MET A   1      32.676  11.938 -21.927  1.00  0.00           H  
ATOM     18  HB2 MET A   1      33.920  12.912 -21.229  1.00  0.00           H  
ATOM     19  HG3 MET A   1      31.724  13.984 -19.996  1.00  0.00           H  
ATOM     20  HG2 MET A   1      31.018  13.460 -21.499  1.00  0.00           H  
ATOM     21  HE1 MET A   1      32.982  15.498 -24.086  1.00  0.00           H  
ATOM     22  HE2 MET A   1      33.215  13.815 -23.558  1.00  0.00           H  
ATOM     23  HE3 MET A   1      31.571  14.475 -23.726  1.00  0.00           H  
ATOM     24  N   THR A   2      30.712  11.223 -18.741  1.00  9.98           N  
ATOM     25  CA  THR A   2      29.469  10.501 -18.503  1.00  8.85           C  
ATOM     26  C   THR A   2      28.342  11.463 -18.217  1.00 11.00           C  
ATOM     27  O   THR A   2      28.506  12.405 -17.424  1.00  9.24           O  
ATOM     28  CB  THR A   2      29.651   9.536 -17.306  1.00 15.81           C  
ATOM     29  OG1 THR A   2      30.789   8.703 -17.531  1.00 13.83           O  
ATOM     30  CG2 THR A   2      28.415   8.664 -17.034  1.00 15.49           C  
ATOM     31  H   THR A   2      30.915  12.004 -18.134  1.00  0.00           H  
ATOM     32  HA  THR A   2      29.222   9.920 -19.391  1.00  0.00           H  
ATOM     33  HB  THR A   2      29.843  10.135 -16.416  1.00  0.00           H  
ATOM     34  HG1 THR A   2      30.901   8.105 -16.788  1.00  0.00           H  
ATOM     35 HG21 THR A   2      28.610   8.012 -16.183  1.00  0.00           H  
ATOM     36 HG22 THR A   2      27.560   9.303 -16.813  1.00  0.00           H  
ATOM     37 HG23 THR A   2      28.197   8.058 -17.913  1.00  0.00           H  
ATOM     38  N   GLU A   3      27.186  11.203 -18.842  1.00  8.87           N  
ATOM     39  CA  GLU A   3      25.982  11.973 -18.580  1.00  7.86           C  
ATOM     40  C   GLU A   3      25.238  11.354 -17.409  1.00 11.09           C  
ATOM     41  O   GLU A   3      25.183  10.124 -17.284  1.00 10.54           O  
ATOM     42  CB  GLU A   3      25.055  11.978 -19.791  1.00  9.04           C  
ATOM     43  CG  GLU A   3      25.462  12.978 -20.839  1.00 12.16           C  
ATOM     44  CD  GLU A   3      24.509  13.090 -22.010  1.00 19.31           C  
ATOM     45  OE1 GLU A   3      24.886  13.774 -22.981  1.00 11.19           O  
ATOM     46  OE2 GLU A   3      23.403  12.500 -21.976  1.00 12.96           O1-
ATOM     47  H   GLU A   3      27.134  10.454 -19.517  1.00  0.00           H  
ATOM     48  HA  GLU A   3      26.256  12.998 -18.332  1.00  0.00           H  
ATOM     49  HB3 GLU A   3      24.036  12.188 -19.466  1.00  0.00           H  
ATOM     50  HB2 GLU A   3      25.030  10.981 -20.232  1.00  0.00           H  
ATOM     51  HG3 GLU A   3      26.458  12.730 -21.207  1.00  0.00           H  
ATOM     52  HG2 GLU A   3      25.581  13.958 -20.376  1.00  0.00           H  
ATOM     53  NT  GLU A   3      24.622  12.170 -16.482  1.00  0.00           N  
ATOM     54  CAT GLU A   3      23.907  11.584 -15.358  1.00  0.00           C  
ATOM     55  HT  GLU A   3      24.667  13.173 -16.584  1.00  0.00           H  
ATOM     56 1HA  GLU A   3      23.976  10.475 -15.428  1.00  0.00           H  
ATOM     57 2HA  GLU A   3      24.361  11.929 -14.402  1.00  0.00           H  
ATOM     58 3HA  GLU A   3      22.839  11.897 -15.386  1.00  0.00           H  
ENDMDL
END 
</pre>

Code:
```python
from simtk.openmm.app import PDBFile
from simtk.openmm import app
from simtk import unit
from simtk.openmm import Platform
from simtk.openmm import LangevinIntegrator

print('building protein and solvating...')
# Load the force field parameters through OpenMM.
omm_forcefield = app.ForceField('charmm36.xml','charmm36/water.xml')

# Load the PDB file.
prot_pdb_file = PDBFile('final_pdb_git_edit.pdb') 
modeller = app.Modeller(prot_pdb_file.topology, prot_pdb_file.positions)
top = prot_pdb_file.topology

## ADDING EXTRA BONDS ##
# Adding extra bonds to the first residue
res = [res for res in top.residues()][0]
atoms = [atom for atom in res.atoms()]
bonds = [bond for bond in res.bonds()]
top.addBond(atoms[0],atoms[3])  
top.addBond(atoms[0],atoms[4])  
top.addBond(atoms[0],atoms[5])  
top.addBond(atoms[0],atoms[1])  
top.addBond(atoms[1],atoms[2])  
top.addBond(atoms[1],atoms[6])   

res = [res for res in top.residues()][0]
bonds = [bond for bond in res.bonds()]

# Adding extra bonds to the last residue
res = [res for res in top.residues()][-1]
atoms = [atom for atom in top.atoms()]
bonds = [bond for bond in res.bonds()]
top.addBond(atoms[39],atoms[52])
top.addBond(atoms[52],atoms[53])
top.addBond(atoms[52],atoms[54])
top.addBond(atoms[53],atoms[55])
top.addBond(atoms[53],atoms[56])
top.addBond(atoms[53],atoms[57])
res = [res for res in top.residues()][-1]
bonds = [bond for bond in res.bonds()]
## FINISHED ADDING EXTRA BONDS ##

print('Adding hydrogens...')
modeller.addHydrogens(omm_forcefield)

# Deleting exra hydrogens
h2 = [atom for atom in modeller.topology.atoms() if atom.name == 'H2' and atom.residue.name == 'MET']
print('atom to be deleted:', h2)
modeller.delete(h2)
h3 = [atom for atom in modeller.topology.atoms() if atom.name == 'H3' and atom.residue.name == 'MET']
print('atom to be deleted:', h3)
modeller.delete(h3)

print('Adding solvent...')
# here we can also add ionic concentration (read addSolvent?)
modeller.addSolvent(omm_forcefield, model='tip3p', padding=1*unit.nanometer, ionicStrength=0.1*unit.molar, positiveIon='Na+', negativeIon='Cl-')

with open('output.pdb', 'w') as f:
    PDBFile.writeFile(modeller.topology, modeller.positions, f)

prot_system = omm_forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, rigidWater=True)


import parmed
print('creating protein structure')
prot_structure = parmed.openmm.load_topology(modeller.topology, prot_system, xyz=modeller.getPositions())
prot_system2 = prot_structure.createSystem(nonbondedMethod=app.PME, rigidWater=True)
```

Output:

<pre>
building protein and solvating...
Adding hydrogens...
atom to be deleted: [Atom 7 (H2) of chain 0 residue 0 (MET)]
atom to be deleted: [Atom 7 (H3) of chain 0 residue 0 (MET)]
Adding solvent...
creating protein structure
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:451: OpenMMWarning: Detected incomplete exceptions. Not supported.
  warnings.warn('Detected incomplete exceptions. Not supported.', OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomNonbondedForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/openmm/topsystem.py:187: OpenMMWarning: Unsupported Force type CustomBondForce
  warnings.warn('Unsupported Force type %s' % type(force).__name__, OpenMMWarning)
Traceback (most recent call last):
  File "__code.py", line 74, in <module>
    prot_system2 = prot_structure.createSystem(nonbondedMethod=app.PME, rigidWater=True)
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/structure.py", line 1995, in createSystem
    raise ParameterError('Cannot createSystem: unknown functional')
parmed.exceptions.ParameterError: Cannot createSystem: unknown functional
</pre>

**Comment by davidlmobley** [comment]
Your PDB file is not correct, in the sense that it's msising CONECT entries (though I can see you're trying to address this by modifying the topology directly). This MAY be contributing to the problem. I haven't seen this error before, however. That said, we DO test that this works for well formed PDBs, so it's quite likely there's an issue with your PDB and/or topology are ending up incorrect somehow

In terms of the GROMACS issue mentioned earlier: From the issues you're mentioning, it sounds like the conversion by ParmEd (which we do not maintain) to GROMACS format is, in this case, not resulting in creation of atom type names and bond type names for all atoms/bonds, meaning that GROMACS basically considers these (required) fields to be empty. They should be filled by text labels (which aren't that important as long as consistent) for the atom type names and bond type names. That said I'm not quite sure the best place to get these in -- it probably is something that needs to happen inside ParmEd, since OpenMM/OpenFF don't really have a notion of (or at least not requirement for) bond type names and atom type names.

**Comment by asgharrazavi** [comment]
The PDB is formatted as Charmm format for capped N- and C-residues. The system built by `modeller.topology` : 

```python
prot_system = omm_forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, rigidWater=True)
```

can be used directly by openmm for simulation as I  outlined in [this ](https://github.com/openmm/openmm/issues/2103)post, and it will be simulated fine.

Although the line `prot_structure = parmed.openmm.load_topology(modeller.topology, prot_system, xyz=modeller.getPositions())` gets executed without error in the above code, I think that the `parmed.openmm.load_topology` is not functioning properly  for charmm formated PDB files.

**Comment by davidlmobley** [comment]
On reading your code from your last excerpt again, it doesn't look like you're using `openforcefield` at all -- https://github.com/openforcefield/openforcefield/issues/731#issuecomment-702737716 -- it looks like you're definitely encountering an OpenMM or a ParmEd problem, so a better place for your report would be on those issue trackers. We're happy to try and help you here with `openforcefield` issues, but it looks like you're trying to use the CHARMM force field with OpenMM, which is a code pathway we have nothing to do with at all.

I can also clarify: my comment about a "not correct" PDB file was partly intended to point out a larger issue where simulation packages tend to play fast-and-loose with the PDB file format and have their own versions of it which are, as you say, "CHARMM format" or "AMBER format" etc., which can be read by those packages but aren't necessarily interoperable. There's only one "official" PDB file format and it's defined by the PDB. Cheminformatics backends like RDKit and OpenEye (which we rely on) can struggle with non-compliant PDB files (e.g. AMBER or CHARMM format) because they may not conform to specs. In your case, the file is missing CONECT entries which are required, so IF you were trying to use `openforcefield` to work with your PDB file, it is possible that would cause problems. But since that's not what you're doing in your last post, well, this is not the origin of the problem.

**Comment by asgharrazavi** [comment]
Leaning more about OpenMM and ParmEd, totally agree that this issue should be moved to ParmEd!
