### ISSUE TITLE
Modeller compatibility with SMIRNOFF force fields

### ISSUE THREAD

**Issue by pschmidtke** [openforcefield/openforcefield#76]
Is it already possible to use openMM Modeller   @#class with openforcefield generated topologies? I tried but failed to do so, so far and the host guest system example also just uses pdbfixer and not the Modeller class.

**Comment by jchodera** [comment]
Would you be able to give a bit more detailed example of what you're trying to do? The SMIRNOFF ForceField class takes OpenMM topologies as input and generates an OpenMM System, and this can then be converted for use with other programs. But I'm unclear on what you mean by "openforcefield generated topologies" since none of our tools generate Topology objects.

**Comment by davidlmobley** [comment]
Perhaps he means the `Topology` objects we provide utility functionality to generate, such as `generateTopologyFromOEMol` or similar.

That said, I think `Modeller` relies pretty extensively on being able to interact with force field library representations of the objects it's dealing with, e.g. with OpenMM XML library files such as for proteins, so it wouldn't surprise me if he's running into trouble there. Most of what is in `Modeller` doesn't look like it would be useful for manipulating things for `openforcefield`, when I've looked at it; at least, I haven't been able to wrap my head around how one would do it. (For example, `addExtraParticles` matches things against residue templates to add extra particles...)

Still, we need to know what specific task is at mind to be able to give advice on how to do it.

**Comment by pschmidtke** [comment]
The basic use case was I have a mol2 input file for the ligand and prepare a topology for that with openforcefield. Then I have a pdb file of the receptor and some important water molecules and I want use openMM to preparation of that and later combine the system (not sure this is possible) and solvate the system. A bit of what you would like to do with tleap. I tried to use modeller to solvate just  a ligand molecule prepared using openforcefield (shuzhe's branch) and this failed for now. Will dig up the error later today. Is this in theory possible? Or should I prepare systems otherwise? Also should I go through github for these things or rather mail / mailing list etc?

**Comment by davidlmobley** [comment]
@pschmidtke - this is as good a place as any.

The way I'd handle the use case you mention is to follow our "mixed forcefield" example, e.g. https://github.com/openforcefield/openforcefield/tree/master/examples/mixedFF_structure .  Specifically, set up your protein/water using "normal" OpenMM procedures and then merge it with the small molecule parameters from SMIRNOFF using `parmEd` as in that example.

It's also possible to use `packmol` to solvate systems independently of the underlying chemistry. The basic problem with the stuff in `Modeller` for these purposes is that it assumes you're working with a system which is parameterized by OpenMM residue template files, I believe, which our stuff is not. 

Does this resolve your issue?

**Comment by pschmidtke** [comment]
ok I'll try this out then. That's a bit more what I'm looking for. I just get the feeling there are various different ways on how to set things up. Will keep you posted if that does the trick.
Cheers!

**Comment by davidlmobley** [comment]
Yes, there are lots of ways of doing things with OpenMM, though not all of them work well with our new world.

As I see it you basically have two general categories of option:
1) Take a system which is already solvated and apply SMIRNOFF to it
2) Apply SMIRNOFF and then solvate your system afterwards

Option (1) I think tends to be somewhat less painful typically, as you're then just taking in, say, a PDB of a solvated system and molecules corresponding to its components and applying parameters. Option (2) tends to require more bookkeeping.

Note I have open a PR, #77, which updates a host-guest binding example to do basically what you want via something like option (2). However, it's OpenEye-centric so it might or might not be super helpful for your purposes.

**Comment by pschmidtke** [comment]
Thanks for the info. Tried to follow PR #77 and got till the final position concatenation done with 
`# Build new position array
omm_pos = omm_pos +  fixer.positions[:len(omm_pos)]`

But here I do not understand what is / should happen. From what I understand you concatenate the omm_pos array with fixer.positions (up to length of omm_pos). From the code (and what I get so far), this would concatenate the original positions of the small molecule, and then the beginning of the fixer positions (also the small molecule as I guess that solvent is added afterwards in the array). So I'm a bit confused here as the final positions won't contain the solvent positions, but two times the small molecule positions. By the way the following line then complains about exactly that : 

`    PDBFile.writeFile(topology_rdk, positions_rdk, open(os.path.join(".", 'complex_solvated.pdb'), 'w'))
  File "/Users/peter/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/pdbfile.py", line 279, in writeFile
    PDBFile.writeModel(topology, positions, file, keepIds=keepIds, extraParticleIdentifier=extraParticleIdentifier)
  File "/Users/peter/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/pdbfile.py", line 326, in writeModel
    raise ValueError('The number of positions must match the number of atoms')
ValueError: The number of positions must match the number of atoms`

I just want to make sure if there's an error in the documentation (jupyter notebook of the host guest system) or I don't get something here (very possible too ;)).

**Comment by jchodera** [comment]
> Thanks for the info. Tried to follow PR #77 and got till the final position concatenation done with
> # Build new position array omm_pos = omm_pos + fixer.positions[:len(omm_pos)]

That doesn't look right. David seems to have a different expression:
```python
omm_pos = omm_pos +  fixer.positions[len(omm_pos):]
```
where he is adding the solvent (stuff that follows `omm_pos`) to the small molecule.

**Comment by davidlmobley** [comment]
@pschmidtke - It's possible I had something wrong (?) in an early version of this notebook, as what I see when I look at my current version of it is exactly what John says (which makes sense to me). Maybe I coded it up wrong originally and fixed it before merging.

Have you tried the current version?

**Comment by pschmidtke** [comment]
Hi David & John,

thanks for your replies. Don’t what happened on my side, but I pulled again and now it’s alright (makes sense to you and me and is the way it should be ;)).

Side question, is there a way to save frcmod files and mol2 files with appropriate atom types using openforcefield/openmm (didn’t check all the documentation yet).

++

peter

On 28 Nov 2017, at 18:29, David L. Mobley <notifications@github.com<mailto:notifications@github.com>> wrote:


@pschmidtke<https://github.com/pschmidtke> - It's possible I had something wrong (?) in an early version of this notebook, as what I see when I look at my current version of it is exactly what John says (which makes sense to me). Maybe I coded it up wrong originally and fixed it before merging.

Have you tried the current version?

**Comment by davidlmobley** [comment]
@pschmidtke - no, no way to go to frcmod files and mol2 files (though you could go to AMBER prmtop and crd files, or the equivalent GROMACS files). This is impossible. 

Partly this is because we no longer have "atom types" per se; we're now using what we call "direct chemical perception". One uses a molecule and assigns parameters by processing the molecule; there is no notion of atom types anymore. 

To give a concrete illustration, GAFF has 13 different "atom types" for carbon; all but three of these are identical in terms of LJ parameters -- so basically it has 13 atom types, but 10 of them are there for "other reasons" not relating to LJ parameters. smirnoff99Frosst has three different sets of LJ parameters for carbon, because there are only three different environments requiring different parameters. Similar things happen with other parameter types. This introduces a huge simplification (you no longer are carrying around, and having to fit, a bunch of additional parameters you didn't want or need) but it makes it impossible to translate a SMIRNOFF back to atom types.

One more concrete illustration: GAFF and AMBER forcefields hav a problem with certain bridgehead atoms between five membered rings; they simply doesn't have enough atom types available to recognize that the single bond joining two five membered rings (in certain situations) should be rotatable and not rigid. Partly this is because atom typing in such situations gets horribly complex. SMIRNOFF has no problem with this, because it can just recognize that the bond in question is a single bond and thus should be rotatable. Translating TO an AMBER format would require that we invent atom types to represent the idea that this single bond should be rotatable, and we don't know how to do that (nor do we have any interest in doing it).

**Comment by davidlmobley** [comment]
(To summarize that another way: No, because we don't use atom types, we use substructure queries, and this is a good thing because it means our force field can be very general while also having few parameters. But it also means it can't be translated to other formats EXCEPT in terms of moving around systems which already have parameters assigned.)
