### ISSUE TITLE
How should SMIRNOFF spec handle multiple occurrences of the same tag?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#96]
How should processing of SMIRNOFF files handle multiple occurrences of the same tag? For example, if `<vdWForce>...</vdWForce>` appears twice (either in the same file, or once each in multiple files), what should the behavior be?

There's really no simple way to specify what order elements should be inserted into a previous section, so the only logical behavior for having a second appearance of the section would be to have the second appearance give rise to a completely separate `Force` object that is processed independently from the first appearance.

Here are some options:

1. **Don't allow multiple occurrences:** We can conclude we really don't need a way to specify two sets of, say, Lennard-Jones terms for each atom. But this might restrict us from separately specifying GBSA parameters if we demand the occur under the `<Electrostatics>` section.

2. **Allow multiple occurrences, but have them be fully independent:** If we have multiple occurrences, they are treated completely independently. If we have both point charges and GBSA treated under the `<Electrostatics>` tag, we'd need to specify the point charges twice if we want the tags to be specified in different files. On the other hand, we could decouple these tags and have a set of charges specified before either how point charges or GBSA is to be specified, like:
```XML
<PartialCharges>
   # just specify how partial charges are to be assigned to the Topology, but not actually used in Force objects yet
</PartialCharges>
<CoulombForce method="PME">
  # specify that these partial charges are supposed to be used in a coulomb force
</CoulombForce>
# ... separate file ...
<GBSAForce method="OBC2">
   # specify that the partial charges defined in <PartialCharges> are to be used in GBSA now
</GBSAForce>
```
I've added the ability to express dependencies between `ForceGenerator` classes, so it would be easy to have the partial charge assignment be required before coulomb force or GBSA force creation. This does go against the nested scheme we discussed, which had been
```XML
<ElectrostaticsForce>
   <PartialCharges>
   </PartialCharges>
   <GBSAForce>
   </GBSAForce>
</ElectrostaticsForce>
```
but it makes for a more easily extensible implementation.

3. **Allow multiple occurrences, coalescing them if they have compatible attributes:** We would treat multiple occurrences independently unless the attributes at the top level were compatible, in which case they would be coalesced, though this may be limited in utility since there is still no simple way to add new types in our hierarchical scheme except to append types to the end. The only real utility would be if we wanted to append very specific types to the end. The order in which we load XML files would also matter in this case, which seems undesirable.

Tagging @davidlmobley @Lnaden @cbayly13 @bannanc

**Comment by jchodera** [comment]
Happy to elaborate further if this is confusion. Addressing this will help me drastically simplify the `ForceField` code.

**Comment by davidlmobley** [comment]
It seems to me like we need Option 3 for practical reasons (because we basically already do things that way):

> Allow multiple occurrences, coalescing them if they have compatible attributes: We would treat multiple occurrences independently unless the attributes at the top level were compatible, in which case they would be coalesced, though this may be limited in utility since there is still no simple way to add new types in our hierarchical scheme except to append types to the end. The only real utility would be if we wanted to append very specific types to the end. The order in which we load XML files would also matter in this case, which seems undesirable.

I think we need this unless there is a way to deal with water and ions that I am missing. Specifically, currently what we're doing is that we have our general small molecule force field, but then we provide separate XML files for water and ion models which the user will load AFTER the general force field in order to specify parameters for the desired water/ion model. This need might go away if we build our own water and ion models, but we want people to be able to select the appropriate water model and ion parameters and the only way I can think of to do this at present is to load a separate XML file which contains specialized SMIRKS patterns for water and have these be appended at the end of the XML. And yes, this means that the order of loading things matters -- but I don't see how to avoid this unless I'm misunderstanding your Option 1 and Option 2, @jchodera .

Am I missing something?

**Comment by jchodera** [comment]
Let's dig into this a little further:

Suppose we will allow the parameters in subsequent `<vdWForce>` sections to be appended if the tag-level parameters (functional form, combining rules, scaling factors, dispersion treatments) are all compatible. That still means that you need to tailor the water model XML file to have the *exact* same tag-level parameters, which still makes it hard to mix-and-match with forcefield parameters. Otherwise, the behavior would be to create entirely separate nonbonded force terms.

Would it be better for us to just integrate water and ion parameters directly into the main `smirnoff99Frosst.offxml` file? It seems like this is a tricker problem, since what I think you really want is "please append these parameters to the end of `<vdWForce>` as long as the potential function form and combining rules are compatible, but I don't care if the other rules about dispersion corrections or scaling factors are compatible or not". But even that may be naive.

I'm leaning toward *disallowing* the same section appearing mutliple times just so we can be restrictive for now and forge ahead with the implementation and spec. Later, we might be able to figure out a very clever and simple way to handle multiple appearances and can always extend the code to handle that, but there's a lot of nuance to worry about here.

**Comment by davidlmobley** [comment]
> Suppose we will allow the parameters in subsequent <vdWForce> sections to be appended if the tag-level parameters (functional form, combining rules, scaling factors, dispersion treatments) are all compatible. That still means that you need to tailor the water model XML file to have the exact same tag-level parameters, which still makes it hard to mix-and-match with forcefield parameters. Otherwise, the behavior would be to create entirely separate nonbonded force terms.

This sounds like it could work well, @jchodera.

> Would it be better for us to just integrate water and ion parameters directly into the main smirnoff99Frosst.offxml file? It seems like this is a tricker problem, since what I think you really want is "please append these parameters to the end of <vdWForce> as long as the potential function form and combining rules are compatible, but I don't care if the other rules about dispersion corrections or scaling factors are compatible or not". But even that may be naive.

No. Because this is sort of a GAFF-like force field and we do not have our own water model at this point, people are going to expect to be able to easily swap water models/ion parameters as they can with other current force fields. 

In other words, people are currently naive, and we do not yet have anything which we want to insist they do instead of being naive (we don't have our own water model, etc.), so we should accommodate what they WANT to do for now until we have data that justifies a switch to doing things differently. I think we can handle this by just making separate SMIRNOFF and water/ion XML files for now, then once we have our own water model we can just put the water model/ion parameters into the same file. :) 

> I'm leaning toward disallowing the same section appearing mutliple times just so we can be restrictive for now and forge ahead with the implementation and spec. Later, we might be able to figure out a very clever and simple way to handle multiple appearances and can always extend the code to handle that, but there's a lot of nuance to worry about here.

Usage-wise, it will help if we can have water/ion parameters be brought in from separate XML files (which means the section should be able to repeat) as noted above. I realize this makes the implementation harder, though, but if we don't do this then if someone wants to swap water models/ions they will have to do it via the API, which is going to be a recipe for someone screwing something up, I think.

**Comment by bannanc** [comment]
I'm trying to catch up on the discussion on github, I agree with @davidlmobley that until we have our own water model (and ion parameters), I can't see a way to avoid having a way for users to add a different water model. Something this made me think of though, is could we treat this similarly to how we are planning to treat <long-ranged treatment> so the smirnoff ffxml file would have our recommended water model and ion parameters that are assigned initially and then if the user insists on having a different model they could add that ffxml file overwriting the parameters with matching SMIRKS? I think this would help people who are new to running simulations and may not have their own opinions about water models use our tools. 

In a way we've already done this with ion parameters as we do have LJ parameters for common salt ions in smirnoff99frosst.

**Comment by davidlmobley** [comment]
@bannanc - yes, that works, except it doesn't work if we *disallow the same section appearing multiple times*, since the only way to override by bringing in another FFXML file is if it repeats the same section. If we disallow that then users would have to use the API (`forcefield.setParameter` or similar) to actually change the water model parameters.

**Comment by bannanc** [comment]
Yes, I guess I was thinking of that falling under agreeing with you in general. 

More broadly than water, I think its worth allowing users to over write parameters using another ffxml file. At least in the AMBER world people are used to being able to do that with frcmod files.

**Comment by davidlmobley** [comment]
That's a great point, yes. Part of what we are trying to enable here is to make it easy for people to try new things; we aren't going to be making it very easy for them to do so if we insist that no one can bring in separate FFXML files that contain the same sections.

**Comment by bannanc** [comment]
Is there a way to combine parameters from two forcefield objects? 
Could we allow this, but where the user would need to acknowledge that they may be overwriting parameters? 
I guess I'm trying to imagine what part of the API the user is actually accessing here. 
Without knowing everything about the new API changes, could I'm imagining something like:
```
ff = ForceField('smirnoff99Frosst.offxml')
tip4p = Forcefield('tip4p.offxml)
my_ff = ff.add_parameters(tip4p, allow_replacement=True)
```
but the `allow_replacement` default would be False to stop people from doing stupid things easily?

**Comment by davidlmobley** [comment]
Basically `ForceField` currently allows you to load multiple XML files at once. 

Perhaps something like what you suggest is a good idea though -- we could make it so you can't load multiple FFXML files at once, but you CAN ask to ADD parameters from one forcefield to another, with the assumption that additional parameters would come after those already present. 

The `allow_replacement` option is a little complex though because one isn't just concerned about replacement, but also hierarchy/overrides, e.g. `[#8H2]` and `[#8X2H2]` and `[#8H2+0]` should all match "just water" (mostly) but they are different patterns, so do they count as a replacement, or not? One has to have a specific molecule in mind to know whether they count as replacement, I think.

**Comment by bannanc** [comment]
I hadn't thought through that all the way. Perhaps just making the extra line or two makes it enough extra work.

**Comment by jchodera** [comment]
The fundamental problems we are wrestling with are:
* If we want to allow new parameters to be added or replaced, we have to somehow specify where on the hierarchical parameter tree they are inserted or replaced. The only really simple way to do that is to allow addition of parameters at the end of a block, with the notion we will always be adding some very special case parameters like waters and ions.
* Even if we do allow this, if the first parameter file changes, say, the LJ mixing rules, this will change the meaning of the second file that is inserted. How so we want to guard against this?

Another possibility might be to find a way for two distinct ForceField objects to be used in succession, with one typing molecules specifically and another more generally. The logic for this quickly becomes complex, however. 

Yet another possibility that would simplify our code would be to rely on a toolchain that uses something like ParmEd (or something with minimal ParmEd like functionality) to let us type part of the system with ForceField (small molecules) and the rest (solvent, ions, and protein) with a different more traditional forcefield. ParmEd is restricted in the kinds of flexibility it can support, but that is probably fine for us in the near term: We can test water models within SMIRNOFF when we consider them as a single file for parameter optimization purposes, but also still support workflows where SMIRNOFF only types part of the system and the rest is typed via some other external system using traditional forcefields.

**Comment by davidlmobley** [comment]
@jchodera : 

The approach I like at present is this: Additional files are allowed to add to the forcefield, but only by adding at the end of the hierarchical parameter tree, with the thought that we are only going to be using this for special cases like water and ions, as you note. And as you said, **we want to allow this only if the other properties specified, such as LJ mixing rules, are identical in subsequent files**, otherwise we should just raise an exception that the two force fields are incompatible.

> Yet another possibility that would simplify our code would be to rely on a toolchain that uses something like ParmEd (or something with minimal ParmEd like functionality) to let us type part of the system with ForceField (small molecules) and the rest (solvent, ions, and protein) with a different more traditional forcefield. 

Yes, we do some of that at present, e.g. for mixing protein force fields with SMIRNOFF. But I don't like that for water/ions, as it takes something which seems like it should be very simple (just apply a SMIRNOFF to the whole system) and muddies it a bit. 

> but also still support workflows where SMIRNOFF only types part of the system and the rest is typed via some other external system using traditional forcefields.

Right. Basically the approach I'd like to see is that we basically assume that we're only going to have single SMIRNOFF files for the whole system, **except for water and ions**. And if someone else wants to use something else (separate protein force field, separate carbohydrate force field, whatever) they are going to have to do it via ParmEd. I don't want to try and support the fully general case, just the common use case of "OK, I want your existing SMIRNOFF but with my favorite water model/ion parameters which use the same combination rules." Does that sound reasonable?

**Comment by jchodera** [comment]
I believe this has been resolved in our current implementation. We can reopen if not.
